const headers = Object.freeze({
  raphacure: {
    booking_id: "Booking ID",
    service: "Service",
    status: "Status",
    visit_type: "Visit Type Id",
    visit_type: "Visit Type",
    date: "Requested On",
    scheduled_on: "Scheduled On",
    appointment_time: "Appointment Time",
    payment_status: "Payment Status",
    name: "Name",
    age: "Age",
    gender: "Gender",
    mobile_no: "Mobile No.",
    email_id: "Email Id.",
    booking_for: "Booking For",
    company: "Company",
    service_group: "Service Group",
    center: "Center",
    city: "City",
    pincode: "Pincode",
    home_collection_address: "Home Collection Address",
    slot_time: "Slot time",
    parent: "Parent",
    comment: "Comment",
    compid: "compid",
    employee_id: "Employee ID",
  },
  neuberg: {
    booking_id: "Reg. No",
    date: "Date",
    service: "Tests",
    net: "Net",
    city: "CITY",
  },
});

module.exports = headers;